/**
 * Timezones supported by WhatsApp (same list as n8n WhatsAble node).
 */
const WHATSAPP_TIMEZONES = [
  { id: 'Pacific/Niue', name: 'Pacific/Niue (GMT-11)' },
  { id: 'Pacific/Pago_Pago', name: 'Pacific/Pago_Pago (GMT-11)' },
  { id: 'Pacific/Honolulu', name: 'Pacific/Honolulu (GMT-10)' },
  { id: 'Pacific/Tahiti', name: 'Pacific/Tahiti (GMT-10)' },
  { id: 'Pacific/Marquesas', name: 'Pacific/Marquesas (GMT-9:30)' },
  { id: 'America/Anchorage', name: 'America/Anchorage (GMT-9)' },
  { id: 'Pacific/Gambier', name: 'Pacific/Gambier (GMT-9)' },
  { id: 'America/Los_Angeles', name: 'America/Los_Angeles (GMT-8)' },
  { id: 'America/Vancouver', name: 'America/Vancouver (GMT-8)' },
  { id: 'America/Denver', name: 'America/Denver (GMT-7)' },
  { id: 'America/Phoenix', name: 'America/Phoenix (GMT-7)' },
  { id: 'America/Chicago', name: 'America/Chicago (GMT-6)' },
  { id: 'America/Mexico_City', name: 'America/Mexico_City (GMT-6)' },
  { id: 'America/New_York', name: 'America/New_York (GMT-5)' },
  { id: 'America/Toronto', name: 'America/Toronto (GMT-5)' },
  { id: 'America/Halifax', name: 'America/Halifax (GMT-4)' },
  { id: 'America/Caracas', name: 'America/Caracas (GMT-4)' },
  { id: 'America/St_Johns', name: 'America/St_Johns (GMT-3:30)' },
  { id: 'America/Sao_Paulo', name: 'America/Sao_Paulo (GMT-3)' },
  { id: 'America/Argentina/Buenos_Aires', name: 'America/Argentina/Buenos_Aires (GMT-3)' },
  { id: 'Atlantic/South_Georgia', name: 'Atlantic/South_Georgia (GMT-2)' },
  { id: 'Atlantic/Azores', name: 'Atlantic/Azores (GMT-1)' },
  { id: 'Europe/London', name: 'Europe/London (GMT+0)' },
  { id: 'Africa/Casablanca', name: 'Africa/Casablanca (GMT+0)' },
  { id: 'Europe/Paris', name: 'Europe/Paris (GMT+1)' },
  { id: 'Europe/Berlin', name: 'Europe/Berlin (GMT+1)' },
  { id: 'Europe/Athens', name: 'Europe/Athens (GMT+2)' },
  { id: 'Africa/Cairo', name: 'Africa/Cairo (GMT+2)' },
  { id: 'Europe/Moscow', name: 'Europe/Moscow (GMT+3)' },
  { id: 'Africa/Nairobi', name: 'Africa/Nairobi (GMT+3)' },
  { id: 'Asia/Tehran', name: 'Asia/Tehran (GMT+3:30)' },
  { id: 'Asia/Dubai', name: 'Asia/Dubai (GMT+4)' },
  { id: 'Europe/Samara', name: 'Europe/Samara (GMT+4)' },
  { id: 'Asia/Kabul', name: 'Asia/Kabul (GMT+4:30)' },
  { id: 'Asia/Karachi', name: 'Asia/Karachi (GMT+5)' },
  { id: 'Asia/Tashkent', name: 'Asia/Tashkent (GMT+5)' },
  { id: 'Asia/Kolkata', name: 'Asia/Kolkata (GMT+5:30)' },
  { id: 'Asia/Kathmandu', name: 'Asia/Kathmandu (GMT+5:45)' },
  { id: 'Asia/Dhaka', name: 'Asia/Dhaka (GMT+6)' },
  { id: 'Asia/Almaty', name: 'Asia/Almaty (GMT+6)' },
  { id: 'Asia/Yangon', name: 'Asia/Yangon (GMT+6:30)' },
  { id: 'Asia/Bangkok', name: 'Asia/Bangkok (GMT+7)' },
  { id: 'Asia/Jakarta', name: 'Asia/Jakarta (GMT+7)' },
  { id: 'Asia/Shanghai', name: 'Asia/Shanghai (GMT+8)' },
  { id: 'Asia/Singapore', name: 'Asia/Singapore (GMT+8)' },
  { id: 'Asia/Tokyo', name: 'Asia/Tokyo (GMT+9)' },
  { id: 'Asia/Seoul', name: 'Asia/Seoul (GMT+9)' },
  { id: 'Australia/Adelaide', name: 'Australia/Adelaide (GMT+9:30)' },
  { id: 'Australia/Darwin', name: 'Australia/Darwin (GMT+9:30)' },
  { id: 'Australia/Sydney', name: 'Australia/Sydney (GMT+10)' },
  { id: 'Pacific/Port_Moresby', name: 'Pacific/Port_Moresby (GMT+10)' },
  { id: 'Australia/Lord_Howe', name: 'Australia/Lord_Howe (GMT+10:30)' },
  { id: 'Pacific/Noumea', name: 'Pacific/Noumea (GMT+11)' },
  { id: 'Asia/Vladivostok', name: 'Asia/Vladivostok (GMT+11)' },
  { id: 'Pacific/Auckland', name: 'Pacific/Auckland (GMT+12)' },
  { id: 'Pacific/Fiji', name: 'Pacific/Fiji (GMT+12)' },
  { id: 'Pacific/Chatham', name: 'Pacific/Chatham (GMT+12:45)' },
  { id: 'Pacific/Tongatapu', name: 'Pacific/Tongatapu (GMT+13)' },
  { id: 'Pacific/Apia', name: 'Pacific/Apia (GMT+13)' },
  { id: 'Pacific/Kiritimati', name: 'Pacific/Kiritimati (GMT+14)' },
];

module.exports = {
  WHATSAPP_TIMEZONES,
};
